/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCompaniesRouteImport } from './routes/_authenticated/companies'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedHrRouteImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedProductionRouteImport } from './routes/_authenticated/production'
import { Route as AuthenticatedUnitsRouteImport } from './routes/_authenticated/units'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit/index'
import { Route as AuthenticatedCompaniesIndexRouteImport } from './routes/_authenticated/companies/index'
import { Route as AuthenticatedCompaniesCompanyIdRouteImport } from './routes/_authenticated/companies/$companyId'
import { Route as AuthenticatedCompaniesNewRouteImport } from './routes/_authenticated/companies/new'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm/index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedGroupsIndexRouteImport } from './routes/_authenticated/groups/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedPurchasesIndexRouteImport } from './routes/_authenticated/purchases/index'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsDocsRouteImport } from './routes/_authenticated/settings/docs'
import { Route as AuthenticatedTeamIndexRouteImport } from './routes/_authenticated/team/index'
import { Route as AuthenticatedUnitsIndexRouteImport } from './routes/_authenticated/units/index'
import { Route as AuthenticatedUnitsUnitIdRouteImport } from './routes/_authenticated/units/$unitId'
import { Route as AuthenticatedUnitsNewRouteImport } from './routes/_authenticated/units/new'
import { Route as ApiPublicOpenapiRouteImport } from './routes/api/public/openapi'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCompaniesRoute = AuthenticatedCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHrRoute = AuthenticatedHrRouteImport.update({
  id: '/hr',
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProductionRoute = AuthenticatedProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsRoute = AuthenticatedUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCompaniesIndexRoute =
  AuthenticatedCompaniesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesCompanyIdRoute =
  AuthenticatedCompaniesCompanyIdRouteImport.update({
    id: '/$companyId',
    path: '/$companyId',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCompaniesNewRoute =
  AuthenticatedCompaniesNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedCompaniesRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/crm/',
  path: '/crm/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGroupsIndexRoute =
  AuthenticatedGroupsIndexRouteImport.update({
    id: '/groups/',
    path: '/groups/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesIndexRoute =
  AuthenticatedPurchasesIndexRouteImport.update({
    id: '/purchases/',
    path: '/purchases/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsDocsRoute =
  AuthenticatedSettingsDocsRouteImport.update({
    id: '/settings/docs',
    path: '/settings/docs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamIndexRoute = AuthenticatedTeamIndexRouteImport.update({
  id: '/team/',
  path: '/team/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUnitsIndexRoute = AuthenticatedUnitsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedUnitsRoute,
} as any)
const AuthenticatedUnitsUnitIdRoute =
  AuthenticatedUnitsUnitIdRouteImport.update({
    id: '/$unitId',
    path: '/$unitId',
    getParentRoute: () => AuthenticatedUnitsRoute,
  } as any)
const AuthenticatedUnitsNewRoute = AuthenticatedUnitsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedUnitsRoute,
} as any)
const ApiPublicOpenapiRoute = ApiPublicOpenapiRouteImport.update({
  id: '/api/public/openapi',
  path: '/api/public/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/production': typeof AuthenticatedProductionRoute
  '/units': typeof AuthenticatedUnitsRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/settings/docs': typeof AuthenticatedSettingsDocsRoute
  '/units/$unitId': typeof AuthenticatedUnitsUnitIdRoute
  '/units/new': typeof AuthenticatedUnitsNewRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/groups/': typeof AuthenticatedGroupsIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/team/': typeof AuthenticatedTeamIndexRoute
  '/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hr': typeof AuthenticatedHrRoute
  '/production': typeof AuthenticatedProductionRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth': typeof AuthIndexRoute
  '/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/settings/docs': typeof AuthenticatedSettingsDocsRoute
  '/units/$unitId': typeof AuthenticatedUnitsUnitIdRoute
  '/units/new': typeof AuthenticatedUnitsNewRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/companies': typeof AuthenticatedCompaniesIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/groups': typeof AuthenticatedGroupsIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/purchases': typeof AuthenticatedPurchasesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/team': typeof AuthenticatedTeamIndexRoute
  '/units': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_authenticated/companies': typeof AuthenticatedCompaniesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hr': typeof AuthenticatedHrRoute
  '/_authenticated/production': typeof AuthenticatedProductionRoute
  '/_authenticated/units': typeof AuthenticatedUnitsRouteWithChildren
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/': typeof AuthIndexRoute
  '/_authenticated/companies/$companyId': typeof AuthenticatedCompaniesCompanyIdRoute
  '/_authenticated/companies/new': typeof AuthenticatedCompaniesNewRoute
  '/_authenticated/settings/docs': typeof AuthenticatedSettingsDocsRoute
  '/_authenticated/units/$unitId': typeof AuthenticatedUnitsUnitIdRoute
  '/_authenticated/units/new': typeof AuthenticatedUnitsNewRoute
  '/api/public/openapi': typeof ApiPublicOpenapiRoute
  '/api/public/products': typeof ApiPublicProductsRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/companies/': typeof AuthenticatedCompaniesIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/groups/': typeof AuthenticatedGroupsIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/purchases/': typeof AuthenticatedPurchasesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/team/': typeof AuthenticatedTeamIndexRoute
  '/_authenticated/units/': typeof AuthenticatedUnitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/companies'
    | '/dashboard'
    | '/hr'
    | '/production'
    | '/units'
    | '/auth/reset-password'
    | '/auth/'
    | '/companies/$companyId'
    | '/companies/new'
    | '/settings/docs'
    | '/units/$unitId'
    | '/units/new'
    | '/api/public/openapi'
    | '/api/public/products'
    | '/audit/'
    | '/companies/'
    | '/crm/'
    | '/finance/'
    | '/groups/'
    | '/inventory/'
    | '/products/'
    | '/purchases/'
    | '/sales/'
    | '/settings/'
    | '/team/'
    | '/units/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/hr'
    | '/production'
    | '/auth/reset-password'
    | '/auth'
    | '/companies/$companyId'
    | '/companies/new'
    | '/settings/docs'
    | '/units/$unitId'
    | '/units/new'
    | '/api/public/openapi'
    | '/api/public/products'
    | '/audit'
    | '/companies'
    | '/crm'
    | '/finance'
    | '/groups'
    | '/inventory'
    | '/products'
    | '/purchases'
    | '/sales'
    | '/settings'
    | '/team'
    | '/units'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/companies'
    | '/_authenticated/dashboard'
    | '/_authenticated/hr'
    | '/_authenticated/production'
    | '/_authenticated/units'
    | '/auth/reset-password'
    | '/auth/'
    | '/_authenticated/companies/$companyId'
    | '/_authenticated/companies/new'
    | '/_authenticated/settings/docs'
    | '/_authenticated/units/$unitId'
    | '/_authenticated/units/new'
    | '/api/public/openapi'
    | '/api/public/products'
    | '/_authenticated/audit/'
    | '/_authenticated/companies/'
    | '/_authenticated/crm/'
    | '/_authenticated/finance/'
    | '/_authenticated/groups/'
    | '/_authenticated/inventory/'
    | '/_authenticated/products/'
    | '/_authenticated/purchases/'
    | '/_authenticated/sales/'
    | '/_authenticated/settings/'
    | '/_authenticated/team/'
    | '/_authenticated/units/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiPublicOpenapiRoute: typeof ApiPublicOpenapiRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/companies': {
      id: '/_authenticated/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AuthenticatedCompaniesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/production': {
      id: '/_authenticated/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof AuthenticatedProductionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units': {
      id: '/_authenticated/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AuthenticatedUnitsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/companies/': {
      id: '/_authenticated/companies/'
      path: '/'
      fullPath: '/companies/'
      preLoaderRoute: typeof AuthenticatedCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/$companyId': {
      id: '/_authenticated/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AuthenticatedCompaniesCompanyIdRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/companies/new': {
      id: '/_authenticated/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof AuthenticatedCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedCompaniesRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/crm'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/groups/': {
      id: '/_authenticated/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof AuthenticatedGroupsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/': {
      id: '/_authenticated/purchases/'
      path: '/purchases'
      fullPath: '/purchases/'
      preLoaderRoute: typeof AuthenticatedPurchasesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/docs': {
      id: '/_authenticated/settings/docs'
      path: '/settings/docs'
      fullPath: '/settings/docs'
      preLoaderRoute: typeof AuthenticatedSettingsDocsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/team/': {
      id: '/_authenticated/team/'
      path: '/team'
      fullPath: '/team/'
      preLoaderRoute: typeof AuthenticatedTeamIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/units/': {
      id: '/_authenticated/units/'
      path: '/'
      fullPath: '/units/'
      preLoaderRoute: typeof AuthenticatedUnitsIndexRouteImport
      parentRoute: typeof AuthenticatedUnitsRoute
    }
    '/_authenticated/units/$unitId': {
      id: '/_authenticated/units/$unitId'
      path: '/$unitId'
      fullPath: '/units/$unitId'
      preLoaderRoute: typeof AuthenticatedUnitsUnitIdRouteImport
      parentRoute: typeof AuthenticatedUnitsRoute
    }
    '/_authenticated/units/new': {
      id: '/_authenticated/units/new'
      path: '/new'
      fullPath: '/units/new'
      preLoaderRoute: typeof AuthenticatedUnitsNewRouteImport
      parentRoute: typeof AuthenticatedUnitsRoute
    }
    '/api/public/openapi': {
      id: '/api/public/openapi'
      path: '/api/public/openapi'
      fullPath: '/api/public/openapi'
      preLoaderRoute: typeof ApiPublicOpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedCompaniesRouteChildren {
  AuthenticatedCompaniesCompanyIdRoute: typeof AuthenticatedCompaniesCompanyIdRoute
  AuthenticatedCompaniesNewRoute: typeof AuthenticatedCompaniesNewRoute
  AuthenticatedCompaniesIndexRoute: typeof AuthenticatedCompaniesIndexRoute
}

const AuthenticatedCompaniesRouteChildren: AuthenticatedCompaniesRouteChildren =
  {
    AuthenticatedCompaniesCompanyIdRoute: AuthenticatedCompaniesCompanyIdRoute,
    AuthenticatedCompaniesNewRoute: AuthenticatedCompaniesNewRoute,
    AuthenticatedCompaniesIndexRoute: AuthenticatedCompaniesIndexRoute,
  }

const AuthenticatedCompaniesRouteWithChildren =
  AuthenticatedCompaniesRoute._addFileChildren(
    AuthenticatedCompaniesRouteChildren,
  )

interface AuthenticatedUnitsRouteChildren {
  AuthenticatedUnitsUnitIdRoute: typeof AuthenticatedUnitsUnitIdRoute
  AuthenticatedUnitsNewRoute: typeof AuthenticatedUnitsNewRoute
  AuthenticatedUnitsIndexRoute: typeof AuthenticatedUnitsIndexRoute
}

const AuthenticatedUnitsRouteChildren: AuthenticatedUnitsRouteChildren = {
  AuthenticatedUnitsUnitIdRoute: AuthenticatedUnitsUnitIdRoute,
  AuthenticatedUnitsNewRoute: AuthenticatedUnitsNewRoute,
  AuthenticatedUnitsIndexRoute: AuthenticatedUnitsIndexRoute,
}

const AuthenticatedUnitsRouteWithChildren =
  AuthenticatedUnitsRoute._addFileChildren(AuthenticatedUnitsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedCompaniesRoute: typeof AuthenticatedCompaniesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHrRoute: typeof AuthenticatedHrRoute
  AuthenticatedProductionRoute: typeof AuthenticatedProductionRoute
  AuthenticatedUnitsRoute: typeof AuthenticatedUnitsRouteWithChildren
  AuthenticatedSettingsDocsRoute: typeof AuthenticatedSettingsDocsRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedGroupsIndexRoute: typeof AuthenticatedGroupsIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedPurchasesIndexRoute: typeof AuthenticatedPurchasesIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedTeamIndexRoute: typeof AuthenticatedTeamIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCompaniesRoute: AuthenticatedCompaniesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHrRoute: AuthenticatedHrRoute,
  AuthenticatedProductionRoute: AuthenticatedProductionRoute,
  AuthenticatedUnitsRoute: AuthenticatedUnitsRouteWithChildren,
  AuthenticatedSettingsDocsRoute: AuthenticatedSettingsDocsRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedGroupsIndexRoute: AuthenticatedGroupsIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedPurchasesIndexRoute: AuthenticatedPurchasesIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedTeamIndexRoute: AuthenticatedTeamIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AuthRouteChildren {
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiPublicOpenapiRoute: ApiPublicOpenapiRoute,
  ApiPublicProductsRoute: ApiPublicProductsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
